# Generated by Django 3.2.8 on 2021-12-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('data_typed_items', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('github_link', models.URLField(null=True)),
                ('linkedin_Link', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
