# Generated by Django 3.2.8 on 2021-12-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211208_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='linkedin_Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SkillLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HTMLSkillLevel', models.IntegerField(max_length=100)),
                ('CSSSkillLevel', models.IntegerField(max_length=100)),
                ('JSSkillLevel', models.IntegerField(max_length=100)),
                ('PythonSkillLevel', models.IntegerField(max_length=100)),
                ('PhotoshopSkillLevel', models.IntegerField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.basicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.basicinfo')),
            ],
        ),
    ]
