# Generated by Django 3.2.8 on 2021-12-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20211208_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillLevels',
            new_name='SkillLevel',
        ),
    ]
