# Generated by Django 3.2.8 on 2021-12-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_skilllevels_skilllevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.IntegerField(max_length=100)),
                ('CSSSkillLevel', models.IntegerField(max_length=100)),
                ('JSSkillLevel', models.IntegerField(max_length=100)),
                ('PythonSkillLevel', models.IntegerField(max_length=100)),
                ('PhotoshopSkillLevel', models.IntegerField(max_length=100)),
            ],
        ),
    ]
