# Generated by Django 3.2.8 on 2021-12-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
