# Generated by Django 3.2.8 on 2021-12-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactU',
        ),
    ]
