# Generated by Django 3.2.8 on 2021-12-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_contactus_contactu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactU',
            new_name='ContactUs',
        ),
    ]
