# Generated by Django 3.2.8 on 2021-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=250, verbose_name="person's first name")),
                ('Email', models.EmailField(max_length=254, verbose_name="person's email")),
                ('Phone_Number', models.IntegerField(verbose_name="person's phone number")),
                ('Location', models.CharField(max_length=100, verbose_name="person's short address")),
                ('Github_Link', models.CharField(max_length=250, verbose_name="person's github link")),
            ],
        ),
    ]
